name: build and test

on:
  push:
  pull_request:
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '7.0.306'
  WORKING_DIRECTORY: src/ORB.WebHost

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY}}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY}}
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{ env.WORKING_DIRECTORY}}
